version: "3"

services:
  user-back:
    build: ./backend_test
    image: user-back
    environment:
      - PORT=3001
    ports:
      - "3001:3001"

  user-front:
    build: ./frontend_test
    image: user-front
    # Mesmo que `docker run -t`
    tty: true
    # Mesmo que `docker run -i`
    stdin_open: true
    environment:
      - BACK_URL=http://localhost:3001/sistema
    ports:
      - "3000:3000"